from django.db import models
from django.conf import settings

class ApplicationNote(models.Model):
    """
    Stores internal notes added during the application review process.
    Can be manually added by agents/managers or auto-generated by the system.
    """
    class NoteType(models.TextChoices):
        SYSTEM_VALIDATION = 'system_validation', 'System Validation Note'
        AGENT_REVIEW = 'agent_review', 'Agent Review Note'
        MANAGER_REMARK = 'manager_remark', 'Manager Remark'
        ESCALATION_REASON = 'escalation_reason', 'Escalation Reason'

    application = models.ForeignKey(
        'Application',
        on_delete=models.CASCADE,
        related_name='notes',
        help_text="The application this note belongs to."
    )

    note_type = models.CharField(
        'Note Type',
        max_length=30,
        choices=NoteType.choices,
        default=NoteType.AGENT_REVIEW
    )

    content = models.TextField(
        'Note Content',
        help_text="The actual note, validation result, or remark."
    )

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='application_notes_created',
        help_text="User who created the note (null for system-generated notes)."
    )

    is_confidential = models.BooleanField(
        'Is Confidential',
        default=False,
        help_text="If true, only visible to managers/landlords, not general agents."
    )

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Application Note'
        verbose_name_plural = 'Application Notes'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['application', 'created_at']),
        ]

    def __str__(self):
        creator = self.created_by.email if self.created_by else "System"
        return f"[{self.get_note_type_display()}] by {creator} on {self.created_at.strftime('%Y-%m-%d')}"