# Generated by Django 5.0.6 on 2026-06-12 23:02

import apps.accounts.utils.validators
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[apps.accounts.utils.validators.validate_strict_email], verbose_name='Email Address')),
                ('phone', models.CharField(help_text='Format: +254712345678 or 0712345678', max_length=15, unique=True, validators=[apps.accounts.utils.validators.validate_phone_number], verbose_name='Phone Number')),
                ('role', models.CharField(choices=[('admin', 'System Administrator'), ('landlord', 'Landlord / Property Owner'), ('agency', 'Real Estate Agency'), ('agent', 'Agency Agent'), ('caretaker', 'Property Caretaker'), ('tenant', 'Tenant')], default='tenant', max_length=20, verbose_name='User Role')),
                ('is_verified', models.BooleanField(default=False, help_text='True if user has submitted and passed ID/KRA verification.', verbose_name='Identity Verified')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='Active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('child', 'Child'), ('relative', 'Relative'), ('friend', 'Friend'), ('other', 'Other')], max_length=20, verbose_name='Relationship')),
                ('phone_number', models.CharField(help_text='Format: +254712345678 or 0712345678', max_length=15, validators=[apps.accounts.utils.validators.validate_phone_number], verbose_name='Phone Number')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City of Residence')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Primary Contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user this emergency contact belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Next of Kin',
                'verbose_name_plural': 'Next of Kin Contacts',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('national_id', models.CharField(blank=True, help_text='7 or 8 digit National ID number (Required for Landlords/Agencies).', max_length=8, null=True, unique=True, validators=[apps.accounts.utils.validators.validate_national_id], verbose_name='National ID')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Physical Address')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/photos/', verbose_name='Profile Photo')),
                ('profile_complete', models.BooleanField(default=False, verbose_name='Profile Complete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document_front', models.FileField(blank=True, help_text='Clear photo of National ID or Passport front.', null=True, upload_to='verifications/ids/', verbose_name='ID/Passport Front')),
                ('id_document_back', models.FileField(blank=True, help_text='Clear photo of National ID back (if applicable).', null=True, upload_to='verifications/ids/', verbose_name='ID/Passport Back')),
                ('kra_pin', models.CharField(blank=True, help_text='Format: A012345678B', max_length=11, null=True, validators=[apps.accounts.utils.validators.validate_kra_pin], verbose_name='Personal KRA PIN')),
                ('kra_tax_compliance_cert', models.FileField(blank=True, help_text='Valid, up-to-date KRA Tax Compliance Certificate.', null=True, upload_to='verifications/tax/', verbose_name='KRA Tax Compliance Certificate')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('resubmit', 'Resubmission Required')], default='pending', max_length=20, verbose_name='Verification Status')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection/Resubmission Reason')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this verification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='The user being verified.', on_delete=django.db.models.deletion.CASCADE, related_name='verification_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Verification',
                'verbose_name_plural': 'User Verifications',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_verified'], name='accounts_us_role_120ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx'),
        ),
        migrations.AddIndex(
            model_name='nextofkin',
            index=models.Index(fields=['user', 'is_primary'], name='accounts_ne_user_id_aa1293_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'profile_complete'], name='accounts_pr_user_id_c92f06_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['status'], name='accounts_ve_status_b70e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['user', 'status'], name='accounts_ve_user_id_b1d249_idx'),
        ),
    ]
