# Generated by Django 5.0.6 on 2026-06-16 08:14

import apps.accounts.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: +254712345678 or 0712345678', max_length=25, null=True, unique=True, validators=[apps.accounts.utils.validators.validate_phone_number], verbose_name='Phone Number'),
        ),
    ]
