# Generated by Django 5.0.6 on 2026-06-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_phone_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requires_password_change',
            field=models.BooleanField(default=False, help_text='If True, the user will be forced to change their temporary password on next login.', verbose_name='Requires Password Change'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True if user has submitted and passed ID/KRA verification. (Tenants do not require this).', verbose_name='Identity Verified'),
        ),
    ]
