# Generated by Django 5.0.6 on 2026-06-12 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenancy_type', models.CharField(choices=[('rental', 'Rental'), ('lease', 'Lease')], default='rental', max_length=20, verbose_name='Tenancy Type')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rent Amount')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Deposit Amount')),
                ('service_charge_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Service Charge')),
                ('deposit_paid', models.BooleanField(default=False, verbose_name='Deposit Paid')),
                ('service_charge_paid', models.BooleanField(default=False, verbose_name='Service Charge Paid')),
                ('deposit_waived', models.BooleanField(default=False, verbose_name='Deposit Waived')),
                ('service_charge_waived', models.BooleanField(default=False, verbose_name='Service Charge Waived')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('suspended', 'Suspended'), ('extended', 'Extended'), ('terminated', 'Terminated'), ('transferred', 'Transferred'), ('expired', 'Expired')], default='pending_payment', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this tenancy (tenant, manager, landlord, or agency).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenancies', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(help_text='The parent property (denormalized for faster querying).', on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='properties.property')),
                ('tenant', models.ForeignKey(help_text='The tenant occupying the unit.', on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(help_text='The specific unit being occupied.', on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Tenancy',
                'verbose_name_plural': 'Tenancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Is Occupied')),
                ('occupancy_start_date', models.DateField(blank=True, null=True, verbose_name='Occupancy Start Date')),
                ('occupancy_end_date', models.DateField(blank=True, null=True, verbose_name='Occupancy End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_tenant', models.ForeignKey(blank=True, help_text='The tenant currently occupying this unit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_occupancies', to=settings.AUTH_USER_MODEL)),
                ('unit', models.OneToOneField(help_text='The unit being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_record', to='properties.unit')),
                ('active_tenancy', models.OneToOneField(blank=True, help_text='The active tenancy driving this occupancy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupancy_record', to='tenancy.tenancy')),
            ],
            options={
                'verbose_name': 'Occupancy Record',
                'verbose_name_plural': 'Occupancy Records',
            },
        ),
        migrations.CreateModel(
            name='MoveInOutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('move_in', 'Move In'), ('move_out', 'Move Out')], max_length=20, verbose_name='Event Type')),
                ('scheduled_date', models.DateField(verbose_name='Scheduled Date')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Actual Date')),
                ('condition_report_notes', models.TextField(blank=True, help_text='Notes on the state of the unit (e.g., existing damages, cleanliness).', null=True, verbose_name='Condition Report Notes')),
                ('keys_handed_over', models.BooleanField(default=False, verbose_name='Keys Handed Over')),
                ('utilities_transferred', models.BooleanField(default=False, verbose_name='Utilities Transferred/Activated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conducted_by', models.ForeignKey(help_text='Manager or agent who conducted the move-in/out inspection.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_move_records', to=settings.AUTH_USER_MODEL)),
                ('tenancy', models.ForeignKey(help_text='The tenancy associated with this move event.', on_delete=django.db.models.deletion.CASCADE, related_name='move_records', to='tenancy.tenancy')),
            ],
            options={
                'verbose_name': 'Move In/Out Record',
                'verbose_name_plural': 'Move In/Out Records',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='TenancyAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('rental', 'Standard Rental Agreement'), ('lease', 'Fixed-Term Lease'), ('short_stay', 'Short Stay Agreement')], default='rental', max_length=20, verbose_name='Agreement Type')),
                ('start_date', models.DateField(verbose_name='Agreement Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Agreement End Date')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Specific rules, house rules, or custom clauses for this tenancy.', null=True, verbose_name='Terms and Conditions')),
                ('digital_signature_url', models.URLField(blank=True, help_text='Link to the e-signed document or signature verification.', null=True, verbose_name='Digital Signature URL')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('signed', 'Signed & Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenancy', models.OneToOneField(help_text='The tenancy this agreement belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='tenancy.tenancy')),
            ],
            options={
                'verbose_name': 'Tenancy Agreement',
                'verbose_name_plural': 'Tenancy Agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenancyExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_new_end_date', models.DateField(help_text='The date the tenant wishes to extend the tenancy to.', verbose_name='Requested New End Date')),
                ('proposed_rent_adjustment', models.DecimalField(decimal_places=2, default=0.0, help_text='Any proposed increase or decrease in rent for the extension period.', max_digits=10, verbose_name='Proposed Rent Adjustment')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason for Extension')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_extensions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_extensions', to=settings.AUTH_USER_MODEL)),
                ('tenancy', models.ForeignKey(help_text='The tenancy being extended.', on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='tenancy.tenancy')),
            ],
            options={
                'verbose_name': 'Tenancy Extension',
                'verbose_name_plural': 'Tenancy Extensions',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='TenancyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenancy_type', models.CharField(max_length=20, verbose_name='Tenancy Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('final_status', models.CharField(max_length=50, verbose_name='Final Status')),
                ('termination_reason', models.TextField(blank=True, null=True, verbose_name='Termination Reason')),
                ('manager_notes', models.TextField(blank=True, null=True, verbose_name='Manager Notes')),
                ('performance_score', models.PositiveIntegerField(blank=True, help_text='1-100 score based on payment timeliness and property care.', null=True, verbose_name='Performance Score')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancy_history_records', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancy_history_records', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancy_history_records', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Tenancy History Record',
                'verbose_name_plural': 'Tenancy History Records',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='TenancyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('general', 'General Note'), ('dispute', 'Dispute Record'), ('maintenance', 'Maintenance Issue'), ('handover', 'Handover Instruction'), ('financial', 'Financial Note')], default='general', max_length=20, verbose_name='Note Type')),
                ('content', models.TextField(help_text='The actual note, instruction, or record of conversation.', verbose_name='Note Content')),
                ('is_confidential', models.BooleanField(default=False, help_text='If true, only visible to admins and the property owner/manager, not general agency staff.', verbose_name='Is Confidential')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='The user who created this note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenancy_notes', to=settings.AUTH_USER_MODEL)),
                ('tenancy', models.ForeignKey(help_text='The tenancy this note belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tenancy.tenancy')),
            ],
            options={
                'verbose_name': 'Tenancy Note',
                'verbose_name_plural': 'Tenancy Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenancyTermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_type', models.CharField(choices=[('tenant_request', 'Tenant Request'), ('landlord_request', 'Landlord Request'), ('breach', 'Breach of Contract'), ('expiry', 'Natural Expiry'), ('mutual', 'Mutual Agreement')], max_length=20, verbose_name='Termination Type')),
                ('notes', models.TextField(blank=True, help_text='Detailed explanation or handover notes.', null=True, verbose_name='Termination Notes')),
                ('penalty_applied', models.DecimalField(decimal_places=2, default=0.0, help_text='Any early termination fees or damage deductions.', max_digits=10, verbose_name='Penalty Applied')),
                ('effective_date', models.DateField(help_text='The date the unit is officially vacated and released.', verbose_name='Effective Termination Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(help_text='Manager, landlord, or admin who approved the termination.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_terminations', to=settings.AUTH_USER_MODEL)),
                ('tenancy', models.OneToOneField(help_text='The tenancy being terminated.', on_delete=django.db.models.deletion.PROTECT, related_name='termination_record', to='tenancy.tenancy')),
            ],
            options={
                'verbose_name': 'Tenancy Termination',
                'verbose_name_plural': 'Tenancy Terminations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenancyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason for Transfer')),
                ('transfer_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Transfer Status')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager or landlord who approved the transfer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='properties.property')),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='properties.unit')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transfers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='The tenant requesting the transfer.', on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('to_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='properties.property')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Tenancy Transfer',
                'verbose_name_plural': 'Tenancy Transfers',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='TenancyWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiver_type', models.CharField(choices=[('deposit', 'Deposit Waiver'), ('service_charge', 'Service Charge Waiver'), ('both', 'Both Deposit and Service Charge')], max_length=20, verbose_name='Waiver Type')),
                ('reason', models.TextField(help_text='Justification for waiving the fee (e.g., promotional offer, tenant hardship).', verbose_name='Reason for Waiver')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager, landlord, or admin who approved the waiver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_waivers', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_waivers', to=settings.AUTH_USER_MODEL)),
                ('tenancy', models.ForeignKey(help_text='The tenancy requesting the waiver.', on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='tenancy.tenancy')),
            ],
            options={
                'verbose_name': 'Tenancy Waiver',
                'verbose_name_plural': 'Tenancy Waivers',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['tenant', 'status'], name='tenancy_ten_tenant__5d3b28_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['unit', 'status'], name='tenancy_ten_unit_id_d25307_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['property', 'status'], name='tenancy_ten_propert_0cd10b_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'pending_payment', 'extended'])), fields=('unit',), name='unique_active_tenancy_per_unit'),
        ),
        migrations.AddIndex(
            model_name='occupancy',
            index=models.Index(fields=['unit', 'is_occupied'], name='tenancy_occ_unit_id_564f15_idx'),
        ),
        migrations.AddIndex(
            model_name='moveinoutrecord',
            index=models.Index(fields=['tenancy', 'event_type'], name='tenancy_mov_tenancy_31007d_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancyextension',
            index=models.Index(fields=['tenancy', 'status'], name='tenancy_ten_tenancy_8480a5_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancyhistory',
            index=models.Index(fields=['tenant', 'recorded_at'], name='tenancy_ten_tenant__b7f46e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancyhistory',
            index=models.Index(fields=['property', 'recorded_at'], name='tenancy_ten_propert_06beec_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancynote',
            index=models.Index(fields=['tenancy', 'created_at'], name='tenancy_ten_tenancy_dcfce9_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancynote',
            index=models.Index(fields=['note_type', 'created_at'], name='tenancy_ten_note_ty_9c29c7_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancytermination',
            index=models.Index(fields=['tenancy', 'termination_type'], name='tenancy_ten_tenancy_7fd164_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancytransfer',
            index=models.Index(fields=['tenant', 'transfer_status'], name='tenancy_ten_tenant__52848e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancywaiver',
            index=models.Index(fields=['tenancy', 'status'], name='tenancy_ten_tenancy_55f226_idx'),
        ),
    ]
