# Generated by Django 5.0.6 on 2026-06-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancytransfer',
            name='manager_notes',
            field=models.TextField(blank=True, help_text='Additional notes from the requesting manager/agent for the approving manager.', null=True, verbose_name='Manager Notes'),
        ),
        migrations.AddField(
            model_name='tenancytransfer',
            name='requested_move_in_date',
            field=models.DateField(blank=True, help_text='When the tenant wants to move into the new unit.', null=True, verbose_name='Requested Move-in Date'),
        ),
    ]
