# Generated by Django 5.0.6 on 2026-06-26 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_location_city_alter_location_county'),
        ('tenancy', '0002_tenancytransfer_manager_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenancy',
            name='unique_active_tenancy_per_unit',
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='deposit_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='service_charge_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='service_charge_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='service_charge_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('suspended', 'Suspended'), ('extended', 'Extended'), ('scheduled_for_termination', 'Scheduled for Termination'), ('terminated', 'Terminated'), ('transferred', 'Transferred'), ('expired', 'Expired')], default='pending_payment', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='tenancy_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('lease', 'Lease')], default='rental', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='properties.unit'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'pending_payment', 'extended', 'scheduled_for_termination'])), fields=('unit',), name='unique_active_tenancy_per_unit'),
        ),
    ]
