# Generated by Django 5.0.6 on 2026-06-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_remove_tenancy_unique_active_tenancy_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancywaiver',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='approved', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tenancywaiver',
            name='waiver_type',
            field=models.CharField(choices=[('rent', 'Rent Waiver'), ('deposit', 'Deposit Waiver'), ('service_charge', 'Service Charge Waiver')], max_length=20, verbose_name='Waiver Type'),
        ),
    ]
