# Generated by Django 5.0.6 on 2026-06-12 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Estate / Neighborhood')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street / Road')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='City / Town')),
                ('county', models.CharField(db_index=True, max_length=100, verbose_name='County / State')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('landmark', models.CharField(help_text="e.g., 'Opposite Nairobi Hospital', 'Next to St. Mary's School', 'Behind Total Petrol Station'", max_length=255, verbose_name='Nearby Landmark')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('geohash', models.CharField(blank=True, db_index=True, help_text='For fast radius/geo queries', max_length=12, null=True, verbose_name='Geohash')),
                ('place_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Place ID')),
                ('normalized_address', models.TextField(blank=True, help_text='Concatenated, lowercase address for search', null=True, verbose_name='Normalized Address')),
                ('search_keywords', models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'near mall, quiet, cbd')", max_length=500, null=True, verbose_name='Search Keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Property Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('cover_photo', models.ImageField(blank=True, help_text='Main display image for the property.', null=True, upload_to='properties/covers/', verbose_name='Cover Photo')),
                ('ownership_status', models.CharField(choices=[('owned', 'Owned & Self-Managed'), ('delegated', 'Delegated to Agency'), ('relinquished', 'Relinquished (Agency Full Control)')], db_index=True, default='owned', max_length=20, verbose_name='Ownership Status')),
                ('property_category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('hospitality', 'Hospitality (Short Stay/Hotels)'), ('industrial', 'Industrial'), ('land', 'Land & Plots'), ('mixed_use', 'Mixed Use')], max_length=20, verbose_name='Category')),
                ('property_sub_type', models.CharField(choices=[('apartment', 'Apartment'), ('flat', 'Flat'), ('bungalow', 'Bungalow'), ('mansion', 'Mansion'), ('villa', 'Villa'), ('townhouse', 'Townhouse'), ('maisonette', 'Maisonette'), ('bedsitter', 'Bedsitter'), ('studio', 'Studio Apartment'), ('single_room', 'Single Room'), ('hostel', 'Student Hostel'), ('office_space', 'Office Space'), ('retail_shop', 'Retail Shop'), ('warehouse', 'Warehouse'), ('airbnb', 'Airbnb / Vacation Rental'), ('hotel', 'Hotel'), ('guest_house', 'Guest House'), ('serviced_apartment', 'Serviced Apartment'), ('residential_plot', 'Residential Plot'), ('commercial_land', 'Commercial Land'), ('agricultural_land', 'Agricultural Land')], max_length=30, verbose_name='Sub-Type')),
                ('construction_type', models.CharField(blank=True, choices=[('concrete', 'Concrete'), ('stone', 'Stone'), ('steel_frame', 'Steel Frame'), ('timber', 'Timber'), ('brick', 'Brick'), ('mixed', 'Mixed Materials')], max_length=20, null=True, verbose_name='Construction Type')),
                ('number_of_floors', models.PositiveIntegerField(default=1, verbose_name='Number of Floors')),
                ('total_units_capacity', models.PositiveIntegerField(default=1, help_text='Maximum number of units this property can hold.', verbose_name='Total Units Capacity')),
                ('is_single_unit_property', models.BooleanField(default=False, help_text='If True (e.g., Mansion, Bungalow, Plot), the unit group creation wizard is skipped.', verbose_name='Is Single Unit Property')),
                ('has_water', models.BooleanField(default=True, verbose_name='Has Water')),
                ('has_electricity', models.BooleanField(default=True, verbose_name='Has Electricity')),
                ('has_internet', models.BooleanField(default=False, verbose_name='Has Internet/Wi-Fi')),
                ('has_cctv', models.BooleanField(default=False, verbose_name='Has CCTV Security')),
                ('has_elevator', models.BooleanField(default=False, verbose_name='Has Elevator')),
                ('has_generator', models.BooleanField(default=False, verbose_name='Has Backup Generator')),
                ('has_gym', models.BooleanField(default=False, verbose_name='Has Gym')),
                ('has_swimming_pool', models.BooleanField(default=False, verbose_name='Has Swimming Pool')),
                ('allows_pets', models.BooleanField(default=False, verbose_name='Allows Pets')),
                ('parking_spaces', models.PositiveIntegerField(default=0, verbose_name='Parking Spaces')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='The landlord or agency user who created this property.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL)),
                ('current_manager', models.ForeignKey(blank=True, help_text='The user or agency currently managing operations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to=settings.AUTH_USER_MODEL)),
                ('location', models.OneToOneField(help_text='Geographic and address details.', on_delete=django.db.models.deletion.CASCADE, related_name='property', to='properties.location')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(blank=True, help_text='Main display image for this specific unit.', null=True, upload_to='units/covers/', verbose_name='Unit Cover Photo')),
                ('unit_code', models.CharField(help_text="e.g., 'A-101', 'MANSION-01'", max_length=50, unique=True, verbose_name='Unit Code')),
                ('unit_type', models.CharField(choices=[('single_room', 'Single Room'), ('bedsitter', 'Bedsitter'), ('studio', 'Studio'), ('one_bedroom', '1 Bedroom'), ('two_bedroom', '2 Bedrooms'), ('three_bedroom', '3 Bedrooms'), ('four_plus_bedroom', '4+ Bedrooms'), ('penthouse', 'Penthouse'), ('commercial_space', 'Commercial Space'), ('land_plot', 'Land Plot'), ('parking_bay', 'Parking Bay')], max_length=30, verbose_name='Unit Type')),
                ('floor_number', models.PositiveIntegerField(default=1, verbose_name='Floor Number')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rent Amount')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Deposit Amount')),
                ('service_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Service Charge')),
                ('billing_cycle', models.CharField(choices=[('daily', 'Daily (Short Stay)'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='Billing Cycle')),
                ('billing_date', models.PositiveIntegerField(default=5, help_text='Day rent is due.', verbose_name='Billing Date')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service')], default='available', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_ref', models.ForeignKey(help_text='The parent property.', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['property_ref', 'unit_code'],
            },
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('virtual_tour', 'Virtual Tour (360)'), ('floor_plan', 'Floor Plan')], default='image', max_length=20, verbose_name='Media Type')),
                ('file', models.FileField(upload_to='properties/media/%Y/%m/', verbose_name='Media File')),
                ('url', models.URLField(blank=True, help_text='For external video links (e.g., YouTube, Vimeo)', null=True, verbose_name='External URL')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, help_text='Optional: Link media to a specific unit instead of the whole property.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Property Media',
                'verbose_name_plural': 'Property Media',
                'ordering': ['property_ref', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Block A', 'Wing 1', 'Main Building'. Used to prefix unit codes (e.g., A-101).", max_length=100, verbose_name='Group Name / Prefix')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('unit_type', models.CharField(choices=[('single_room', 'Single Room'), ('bedsitter', 'Bedsitter'), ('studio', 'Studio'), ('one_bedroom', '1 Bedroom'), ('two_bedroom', '2 Bedrooms'), ('three_bedroom', '3 Bedrooms'), ('four_plus_bedroom', '4+ Bedrooms'), ('penthouse', 'Penthouse'), ('commercial_space', 'Commercial Space'), ('land_plot', 'Land Plot'), ('parking_bay', 'Parking Bay')], max_length=30, verbose_name='Unit Type')),
                ('floor_range', models.CharField(help_text="e.g., 'Ground', '1-3', '4-5'. Helps in organizing bulk generation.", max_length=50, verbose_name='Floor Range')),
                ('billing_cycle', models.CharField(choices=[('daily', 'Daily (Short Stay)'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='Billing Cycle')),
                ('billing_date', models.PositiveIntegerField(default=5, help_text='Day of the month/week rent is due (e.g., 5 for 5th of every month).', verbose_name='Billing Date')),
                ('base_rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Rent')),
                ('service_charge_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Service Charge')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Security Deposit')),
                ('currency', models.CharField(default='KES', max_length=3, verbose_name='Currency')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Total Units in Group')),
                ('allows_pets_override', models.BooleanField(blank=True, help_text='If null, inherits from Property.', null=True, verbose_name='Pets Allowed (Override Property)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(help_text='The parent property this group belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='unit_groups', to='properties.property')),
            ],
            options={
                'verbose_name': 'Unit Group',
                'verbose_name_plural': 'Unit Groups',
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_group',
            field=models.ForeignKey(blank=True, help_text='The group this unit belongs to (Null for single-unit properties).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='properties.unitgroup'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_category', 'property_sub_type'], name='properties__propert_89e508_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active', 'ownership_status'], name='properties__is_acti_3833ed_idx'),
        ),
        migrations.AddIndex(
            model_name='unitgroup',
            index=models.Index(fields=['property', 'is_active'], name='properties__propert_c05c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='unitgroup',
            index=models.Index(fields=['billing_cycle', 'unit_type'], name='properties__billing_6ede3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitgroup',
            constraint=models.UniqueConstraint(fields=('property', 'name'), name='unique_unit_group_per_property'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['property_ref', 'status'], name='properties__propert_962371_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_group', 'status'], name='properties__unit_gr_659107_idx'),
        ),
    ]
