# Generated by Django 5.0.6 on 2026-06-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_location_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geohash',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, verbose_name='Geohash'),
        ),
        migrations.AlterField(
            model_name='location',
            name='landmark',
            field=models.CharField(blank=True, help_text="e.g., 'Opposite Nairobi Hospital', 'Next to St. Mary's School'", max_length=255, null=True, verbose_name='Nearby Landmark'),
        ),
        migrations.AlterField(
            model_name='location',
            name='normalized_address',
            field=models.TextField(blank=True, null=True, verbose_name='Normalized Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='search_keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Search Keywords'),
        ),
    ]
