# Generated by Django 5.0.6 on 2026-06-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_location_geohash_alter_location_landmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitgroup',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Primary thumbnail for this unit group.', null=True, upload_to='properties/unit_groups/covers/%Y/%m/', verbose_name='Group Cover Photo'),
        ),
        migrations.AlterField(
            model_name='unitgroup',
            name='allows_pets_override',
            field=models.BooleanField(blank=True, null=True, verbose_name='Pets Allowed (Override Property)'),
        ),
        migrations.AlterField(
            model_name='unitgroup',
            name='billing_date',
            field=models.PositiveIntegerField(default=5, help_text='Day of the month/week rent is due.', verbose_name='Billing Date'),
        ),
        migrations.AlterField(
            model_name='unitgroup',
            name='floor_range',
            field=models.CharField(help_text="e.g., 'Ground', '1-3', '4-5'.", max_length=50, verbose_name='Floor Range'),
        ),
        migrations.AlterField(
            model_name='unitgroup',
            name='name',
            field=models.CharField(help_text="e.g., 'Block A', 'Wing 1'. Used to prefix unit codes.", max_length=100, verbose_name='Group Name / Prefix'),
        ),
    ]
