# Generated by Django 5.0.6 on 2026-06-18 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_unitgroup_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymedia',
            name='unit_group',
            field=models.ForeignKey(blank=True, help_text='Optional: Link media to a specific unit group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='properties.unitgroup'),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('virtual_tour', 'Virtual Tour (360)'), ('floor_plan', 'Floor Plan'), ('document', 'Document (PDF/Deed/ID)')], default='image', max_length=20, verbose_name='Media Type'),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Optional: Link media to a specific individual unit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='properties.unit'),
        ),
    ]
