# Generated by Django 5.0.6 on 2026-06-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertymedia_unit_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitgroup',
            old_name='service_charge_amount',
            new_name='service_charge',
        ),
    ]
