# Generated by Django 5.0.6 on 2026-06-18 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_rename_service_charge_amount_unitgroup_service_charge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(default=False, help_text='If true, this property is visible on the public marketplace.', verbose_name='Published to Marketplace'),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('rental', 'Rental'), ('sale', 'Sale'), ('short_stay', 'Short Stay')], help_text='Determines how the property is categorized on the marketplace (Rental, Sale, Short Stay).', max_length=20, null=True, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active (Wizard Complete)'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_published', 'listing_type'], name='properties__is_publ_e3933b_idx'),
        ),
    ]
