# Generated by Django 5.0.6 on 2026-06-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_is_published_property_listing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='City / Town'),
        ),
        migrations.AlterField(
            model_name='location',
            name='county',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='County / State'),
        ),
    ]
