# Generated by Django 5.0.6 on 2026-06-30 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_alter_agencystaff_options_and_more'),
        ('properties', '0008_alter_location_city_alter_location_county'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_role', models.CharField(choices=[('caretaker', 'Caretaker'), ('agent', 'Agent'), ('property_manager', 'Property Manager')], max_length=30, verbose_name='Operational Role')),
                ('assigned_by_entity_type', models.CharField(choices=[('landlord', 'Direct Landlord Assignment'), ('agency', 'Agency Assignment')], default='landlord', help_text='Tracks whether the landlord or the agency made this assignment.', max_length=20, verbose_name='Assigned By')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by_agency', models.ForeignKey(blank=True, help_text='The agency that made this assignment (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_staff_assignments', to='agencies.agency')),
                ('property', models.ForeignKey(help_text='The property this staff member is assigned to.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='properties.property')),
                ('user', models.ForeignKey(help_text='The user performing the operational role.', on_delete=django.db.models.deletion.CASCADE, related_name='property_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Staff Assignment',
                'verbose_name_plural': 'Property Staff Assignments',
                'indexes': [models.Index(fields=['property', 'is_active'], name='properties__propert_ba188a_idx'), models.Index(fields=['user', 'is_active'], name='properties__user_id_e2223b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='propertystaffassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('property', 'user', 'operational_role'), name='unique_active_role_per_property_user'),
        ),
    ]
