# Generated by Django 5.0.6 on 2026-06-12 23:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('rental', 'Rental'), ('sale', 'For Sale'), ('short_stay', 'Short Stay')], max_length=20, verbose_name='Listing Type')),
                ('cover_photo', models.ImageField(blank=True, help_text='Main image shown on the marketplace landing page.', null=True, upload_to='marketplace/covers/', verbose_name='Landing Page Cover Photo')),
                ('title', models.CharField(max_length=255, verbose_name='Listing Title')),
                ('location_summary', models.CharField(help_text="e.g., 'Kilimani, Nairobi' (Cached for fast grid rendering)", max_length=255, verbose_name='Location Summary')),
                ('min_rent_amount', models.DecimalField(decimal_places=2, help_text='Starting price shown on landing page card.', max_digits=12, verbose_name='Min Rent Amount')),
                ('price_period', models.CharField(blank=True, help_text="e.g., 'per month', 'per night'", max_length=50, null=True, verbose_name='Price Period')),
                ('status', models.CharField(choices=[('active', 'Active'), ('unavailable', 'Unavailable (Fully Occupied)'), ('hidden', 'Hidden'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='properties.property')),
                ('unit_group', models.ForeignKey(blank=True, help_text='Specific unit group (for rental listings). Null if whole property.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='properties.unitgroup')),
            ],
            options={
                'verbose_name': 'Marketplace Listing',
                'verbose_name_plural': 'Marketplace Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('homepage_hero', 'Homepage Hero Banner'), ('featured_section', 'Featured Listings Grid'), ('category_top', 'Category Top (e.g., Top in Nairobi)')], default='featured_section', max_length=30, verbose_name='Placement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank for indefinite featured status.', null=True, verbose_name='End Date')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = higher display priority within the same placement.', verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(help_text='The marketplace listing being featured.', on_delete=django.db.models.deletion.CASCADE, related_name='featured_placements', to='marketplace.listing')),
            ],
            options={
                'verbose_name': 'Featured Listing',
                'verbose_name_plural': 'Featured Listings',
                'ordering': ['-priority', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('search', 'Search Results'), ('featured', 'Featured Section'), ('nearby', 'Nearby / Geo Search'), ('direct', 'Direct Link / Property Detail'), ('recommendation', 'AI Recommendation')], default='direct', help_text='How the user arrived at this listing.', max_length=20, verbose_name='View Source')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='For duplicate view throttling.', null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Agent')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(help_text='The listing that was viewed.', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='marketplace.listing')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user who viewed (null for public visitors).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing View',
                'verbose_name_plural': 'Listing Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('unpublished_at', models.DateTimeField(blank=True, null=True, verbose_name='Unpublished At')),
                ('visibility_status', models.CharField(choices=[('visible', 'Visible on Marketplace'), ('hidden', 'Hidden (Internal Only)'), ('unpublished', 'Unpublished'), ('suspended', 'Suspended by Admin')], default='unpublished', max_length=20, verbose_name='Visibility Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_publications', to=settings.AUTH_USER_MODEL)),
                ('property', models.OneToOneField(help_text='The property being published.', on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='properties.property')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Publication',
                'verbose_name_plural': 'Property Publications',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceVisibilityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('published', 'Published to Marketplace'), ('hidden', 'Hidden from Marketplace'), ('unpublished', 'Unpublished'), ('restored', 'Restored to Visibility'), ('suspended', 'Suspended by Admin')], max_length=20, verbose_name='Action Taken')),
                ('reason', models.TextField(blank=True, help_text='Optional note explaining the action.', null=True, verbose_name='Reason for Change')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('performed_by', models.ForeignKey(help_text='The user (landlord, agency, or admin) who made the change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visibility_changes_performed', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(help_text='The property whose visibility changed.', on_delete=django.db.models.deletion.CASCADE, related_name='visibility_logs', to='properties.property')),
                ('publication', models.ForeignKey(help_text='The publication record that was modified.', on_delete=django.db.models.deletion.CASCADE, related_name='visibility_logs', to='marketplace.propertypublication')),
            ],
            options={
                'verbose_name': 'Marketplace Visibility Log',
                'verbose_name_plural': 'Marketplace Visibility Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text="Optional personal note (e.g., 'Good for family')", null=True, verbose_name='User Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(help_text='The marketplace listing being saved.', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='marketplace.listing')),
                ('user', models.ForeignKey(help_text='The user who saved this listing.', on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Listing',
                'verbose_name_plural': 'Saved Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='Tracks anonymous user searches via session cookie.', max_length=100, null=True, verbose_name='Session ID')),
                ('search_query', models.CharField(blank=True, help_text="Raw text entered in search bar (e.g., '2 bedroom kilimani')", max_length=255, null=True, verbose_name='Search Query')),
                ('filters_applied', models.JSONField(blank=True, default=dict, null=True, verbose_name='Filters Applied')),
                ('results_count', models.PositiveIntegerField(default=0, help_text='Number of properties returned by this search.', verbose_name='Results Count')),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user. Null for anonymous public visitors.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search History Records',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitGroupAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_units', models.PositiveIntegerField(help_text='Total capacity of this unit group', verbose_name='Total Units in Group')),
                ('available_units', models.PositiveIntegerField(help_text='Number of units currently available for rent', verbose_name='Available Units')),
                ('occupied_units', models.PositiveIntegerField(default=0, verbose_name='Occupied Units')),
                ('reserved_units', models.PositiveIntegerField(default=0, help_text='Pending applications', verbose_name='Reserved Units')),
                ('is_marketplace_visible', models.BooleanField(default=True, help_text='Auto-set to False when available_units = 0', verbose_name='Visible in Marketplace')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('unit_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_availability', to='properties.unitgroup')),
            ],
            options={
                'verbose_name': 'Unit Group Availability',
                'verbose_name_plural': 'Unit Group Availabilities',
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'listing_type'], name='marketplace_status_2aa23f_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['property', 'status'], name='marketplace_propert_639e61_idx'),
        ),
        migrations.AddIndex(
            model_name='featuredlisting',
            index=models.Index(fields=['is_active', 'placement', 'start_date'], name='marketplace_is_acti_8b3e87_idx'),
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['listing', 'viewed_at'], name='marketplace_listing_664e29_idx'),
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['source', 'viewed_at'], name='marketplace_source_6b6e05_idx'),
        ),
        migrations.AddIndex(
            model_name='propertypublication',
            index=models.Index(fields=['is_published', 'visibility_status'], name='marketplace_is_publ_98787a_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacevisibilitylog',
            index=models.Index(fields=['property', 'timestamp'], name='marketplace_propert_3b7899_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacevisibilitylog',
            index=models.Index(fields=['performed_by', 'timestamp'], name='marketplace_perform_562973_idx'),
        ),
        migrations.AddIndex(
            model_name='savedlisting',
            index=models.Index(fields=['user', 'created_at'], name='marketplace_user_id_c0a1d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedlisting',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='unique_saved_listing_per_user'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', 'searched_at'], name='marketplace_user_id_ace9a8_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['session_id', 'searched_at'], name='marketplace_session_9fba68_idx'),
        ),
        migrations.AddIndex(
            model_name='unitgroupavailability',
            index=models.Index(fields=['is_marketplace_visible', 'available_units'], name='marketplace_is_mark_44e6dd_idx'),
        ),
    ]
