# Generated by Django 5.0.6 on 2026-08-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_units',
            field=models.IntegerField(default=0, help_text='Number of currently available units. Auto-synced by marketplace signals.', verbose_name='Available Units'),
        ),
    ]
