# Generated by Django 5.0.6 on 2026-06-12 23:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('in_app', 'In-App')], max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Email subject line', max_length=255, null=True)),
                ('body', models.TextField(help_text='Use {variable} placeholders for dynamic content')),
                ('required_variables', models.JSONField(default=list, help_text='List of expected placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('in_app', 'In-App')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('total_delivered', models.PositiveIntegerField(default=0)),
                ('metrics', models.JSONField(default=dict, help_text='Delivery rates, open rates, failures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_comm_campaigns', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_campaigns', to='communications.messagetemplate')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAudience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audience_type', models.CharField(choices=[('role', 'By User Role'), ('property_tenants', 'Tenants of Specific Properties'), ('arrears_list', 'Users with Overdue Balances'), ('custom_list', 'Custom User IDs'), ('system_wide', 'All Active Users')], max_length=20)),
                ('filter_criteria', models.JSONField(default=dict, help_text='Role, property IDs, or custom user list')),
                ('estimated_count', models.PositiveIntegerField(default=0)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='communications.campaign')),
            ],
            options={
                'verbose_name_plural': 'Campaign Audiences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('in_app', 'In-App')], max_length=20)),
                ('message_type', models.CharField(choices=[('system', 'System'), ('transactional', 'Transactional'), ('alert', 'Alert'), ('reminder', 'Reminder'), ('campaign', 'Campaign')], max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], db_index=True, default='queued', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Template ID, campaign ID, or routing info')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(help_text='e.g., africastalking, whatsapp_api, smtp', max_length=50)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='communications.message')),
            ],
            options={
                'verbose_name_plural': 'Delivery Logs',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('tenancy_created', 'Tenancy Created'), ('tenancy_terminated', 'Tenancy Terminated'), ('payment_received', 'Payment Received'), ('invoice_generated', 'Invoice Generated'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('maintenance_updated', 'Maintenance Updated'), ('arrears_alert', 'Arrears Alert')], db_index=True, max_length=30)),
                ('target_user_id', models.UUIDField(blank=True, help_text='Recipient user ID', null=True)),
                ('payload', models.JSONField(default=dict, help_text='Dynamic data for template injection')),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'processed'], name='communicati_event_t_948eac_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('system', 'System'), ('transactional', 'Transactional'), ('alert', 'Alert'), ('reminder', 'Reminder'), ('campaign', 'Campaign')], max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('action_link', models.CharField(blank=True, help_text='Frontend route to navigate', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'status'], name='communicati_recipie_805e80_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['channel', 'created_at'], name='communicati_channel_0e6cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'channel'], name='communicati_status_090554_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='communicati_user_id_8fd9c3_idx'),
        ),
    ]
