# Generated by Django 5.0.6 on 2026-06-12 23:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '__first__'),
        ('payments', '0001_initial'),
        ('properties', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('template_content', models.TextField(help_text='HTML/Jinja template content or raw text with {placeholders}')),
                ('variables', models.JSONField(default=list, help_text="Expected dynamic variables like ['tenant_name', 'rent_amount']")),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g., LEASE, RECEIPT, ID, INSPECTION', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('requires_signature', models.BooleanField(default=False, help_text='Triggers signing workflow if True')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('file_url', models.URLField(help_text='Secure cloud storage link')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('active', 'Active'), ('archived', 'Archived'), ('expired', 'Expired'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Source reference, generation params, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Tenant/agent who must review/sign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property')),
                ('tenancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenancy.tenancy')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.unit')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_docs', to='documents.documenttemplate')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(help_text='e.g., pdf, image, scan', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.document')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Attachment',
                'verbose_name_plural': 'Document Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='documents.documenttype'),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('file_url', models.URLField()),
                ('change_reason', models.TextField(blank=True, help_text='Why this version was created', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation_variables', models.JSONField(blank=True, default=dict, help_text='Snapshot of variables injected into template')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 hash for tamper verification', max_length=64, null=True)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('page_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='applications.application')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_record', to='documents.document')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_generated', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='payments.payment')),
                ('property_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='properties.property')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_instances', to='documents.documenttemplate')),
                ('tenancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='tenancy.tenancy')),
            ],
            options={
                'verbose_name': 'Generated Document',
                'verbose_name_plural': 'Generated Documents',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('uploaded', 'Uploaded'), ('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('signed', 'Signed'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('version_created', 'Version Created')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Signature hash, download timestamp, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='documents.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Audit Log',
                'verbose_name_plural': 'Document Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'action'], name='documents_d_documen_d4c235_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'document_type'], name='documents_d_status_93c4bf_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenancy', 'status'], name='documents_d_tenancy_5134de_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['property', 'unit'], name='documents_d_propert_35bdbc_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['status', 'generated_at'], name='documents_g_status_dbeecc_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['tenancy', 'status'], name='documents_g_tenancy_5792d1_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['payment', 'status'], name='documents_g_payment_a026ca_idx'),
        ),
    ]
