# Generated by Django 5.0.6 on 2026-06-12 23:02

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrears',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('oldest_overdue_date', models.DateField(blank=True, null=True)),
                ('days_overdue', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('current', 'Current'), ('overdue', 'Overdue'), ('escalated', 'Escalated')], db_index=True, default='current', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='arrears_record', to='tenancy.tenancy')),
            ],
            options={
                'ordering': ['-total_outstanding'],
            },
        ),
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cycle_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('billing_day', models.PositiveIntegerField(help_text='Day of month (1-31) or day of week (0-6)')),
                ('grace_period_days', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['cycle_type'],
                'unique_together': {('name', 'cycle_type')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('void', 'Void'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenancy.tenancy')),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('rent', 'Base Rent'), ('service_charge', 'Service Charge'), ('utilities', 'Utilities (Water/Electricity)'), ('late_fee', 'Late Penalty'), ('deposit', 'Security/Utility Deposit'), ('maintenance', 'Maintenance Fee'), ('adjustment', 'Manual Adjustment/Credit'), ('other', 'Other')], db_index=True, max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.PositiveIntegerField(default=1, help_text='For metered utilities or multi-unit charges')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-filled if quantity > 1', max_digits=10, null=True)),
                ('is_taxable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payments.invoice')),
            ],
            options={
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['item_type', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_id', models.CharField(db_index=True, help_text='External Transaction Code (e.g., QJ...7H)', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('reconciled', 'Reconciled')], db_index=True, default='pending', max_length=20)),
                ('account_received_at', models.CharField(help_text='Phone/Paybill that received the funds', max_length=100)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Provider callback data')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('paybill', 'Paybill'), ('till', 'Buy Goods (Till Number)'), ('phone', 'Direct Phone Number')], max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('paybill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('till_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Primary routing account for this property')),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_payment_accounts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_accounts', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAccountVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(help_text='e.g., mpesa_b2c_test, manual_review', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Mpesa transaction ID for test deposit', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocation_type', models.CharField(choices=[('invoice', 'Direct to Invoice'), ('arrears', 'To Overdue Balance'), ('future', 'Credit to Future Rent')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_allocations', to='payments.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.payment')),
            ],
            options={
                'verbose_name_plural': 'Payment Allocations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('penalty_type', models.CharField(choices=[('late_fee', 'Late Fee'), ('insufficient_funds', 'Insufficient Funds Fee'), ('breach', 'Contract Breach Penalty')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='tenancy.tenancy')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('file_url', models.URLField(blank=True, help_text='Link to generated PDF', null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='payments.payment')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='tenancy.tenancy')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('mismatch', 'Mismatch'), ('unallocated', 'Unallocated')], db_index=True, default='unallocated', max_length=20)),
                ('discrepancy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_records', to='payments.payment')),
            ],
            options={
                'ordering': ['-reconciled_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('processed', 'Processed'), ('failed', 'Failed')], default='requested', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_ref', models.CharField(blank=True, help_text='M-Pesa B2C Ref', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='tenancy.tenancy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='balance_record', to='tenancy.tenancy')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_waivers', to='payments.invoice')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_waivers', to='tenancy.tenancy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenancy', 'status'], name='payments_in_tenancy_34dc75_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('property', 'is_default'), name='unique_default_per_property'),
        ),
    ]
