# Generated by Django 5.0.6 on 2026-06-24 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccountverification',
            name='payment_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='payments.paymentaccount'),
            preserve_default=False,
        ),
    ]
