# Generated by Django 5.0.6 on 2026-06-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentaccountverification_payment_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccountverification',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
