# Generated by Django 5.0.6 on 2026-08-24 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentaccountverification_reference'),
        ('tenancy', '0004_alter_tenancywaiver_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at', '-created_at'], 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='paymentaccount',
            options={'verbose_name': 'Settlement Account', 'verbose_name_plural': 'Settlement Accounts'},
        ),
        migrations.AlterModelOptions(
            name='paymentaccountverification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Settlement Account Verification', 'verbose_name_plural': 'Settlement Account Verifications'},
        ),
        migrations.AddField(
            model_name='payment',
            name='account_reference',
            field=models.CharField(blank=True, db_index=True, help_text='The Account Reference used in the STK push (e.g., TEN-12345678 or INV-999)', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenancy',
            field=models.ForeignKey(blank=True, help_text='The tenancy this payment is intended for (crucial for future credits/arrears)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='tenancy.tenancy'),
        ),
        migrations.AddField(
            model_name='paymentaccountverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='account_received_at',
            field=models.CharField(help_text='Phone/Paybill that received the funds (Platform Paybill)', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('reconciled', 'Reconciled'), ('pending_reconciliation', 'Pending Reconciliation')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Primary settlement/payout account for this property/landlord'),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_payment_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentaccountverification',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_allocations', to='payments.invoice'),
        ),
    ]
