from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView, TokenVerifyView

from . import views

# 1. Initialize the DRF Router
router = DefaultRouter()

# 2. Register the ViewSets
router.register(r'profile', views.ProfileViewSet, basename='profile')
router.register(r'next-of-kin', views.NextOfKinViewSet, basename='next-of-kin')
router.register(r'verification', views.VerificationViewSet, basename='verification')
router.register(r'auth', views.AuthViewSet, basename='auth')
router.register(r'manager-tenants', views.ManagerTenantViewSet, basename='manager-tenants')

# ✅ NEW: Register the Applicant Management ViewSet (Lookup & Staff Creation)
router.register(r'applicant-management', views.ApplicantManagementViewSet, basename='applicant-management')

urlpatterns = [
    # ==========================================
    # 1. STANDARD JWT ENDPOINTS (SimpleJWT)
    # ==========================================
    path('refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('verify/', TokenVerifyView.as_view(), name='token_verify'),
    
    # ==========================================
    # 2. VIEWSET ROUTES (Auto-generated by Router)
    # ==========================================
    path('', include(router.urls)),
    
    # ==========================================
    # 3. CRITICAL ALIAS FOR FRONTEND ROUTING
    # ==========================================
    path('user-state/', views.ProfileViewSet.as_view({'get': 'user_state'}), name='user-state'),
]