from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView, TokenVerifyView

from . import views

# 1. Initialize the DRF Router
router = DefaultRouter()

# 2. Register the ViewSets
router.register(r'profile', views.ProfileViewSet, basename='profile')
router.register(r'next-of-kin', views.NextOfKinViewSet, basename='next-of-kin')
router.register(r'verification', views.VerificationViewSet, basename='verification')
router.register(r'auth', views.AuthViewSet, basename='auth')

# ✅ NEW: Register the Manager-Initiated Tenant Creation ViewSet
router.register(r'manager-tenants', views.ManagerTenantViewSet, basename='manager-tenants')

urlpatterns = [
    # ==========================================
    # 1. STANDARD JWT ENDPOINTS (SimpleJWT)
    # ==========================================
    path('refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('verify/', TokenVerifyView.as_view(), name='token_verify'),
    
    # ==========================================
    # 2. VIEWSET ROUTES (Auto-generated by Router)
    # ==========================================
    # This automatically creates:
    # /auth/login/
    # /auth/register/
    # /profile/me/
    # /profile/update/
    # /profile/upgrade/
    # /profile/complete/
    # /next-of-kin/ (GET/POST)
    # /verification/status/
    # /verification/submit/
    # /manager-tenants/create/ (POST) ✅ NEW
    path('', include(router.urls)),
    
    # ==========================================
    # 3. CRITICAL ALIAS FOR FRONTEND ROUTING
    # ==========================================
    # The NB Document strictly requires the frontend to call: GET /api/accounts/user-state/
    # The router creates it at /profile/state/. We add an explicit alias to match the doc exactly.
    path('user-state/', views.ProfileViewSet.as_view({'get': 'user_state'}), name='user-state'),
]