# Generated by Django 5.0.6 on 2026-06-16 08:37

import apps.accounts.utils.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_location_postal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Agency Name')),
                ('registration_number', models.CharField(help_text='Official government registration number.', max_length=100, unique=True, verbose_name='Business Registration Number')),
                ('contact_email', models.EmailField(max_length=254, unique=True, verbose_name='Contact Email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Contact Phone')),
                ('physical_address', models.TextField(verbose_name='Physical Address')),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending_verification', max_length=30, verbose_name='Status')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='The user who initially registered this agency.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('staff_created', 'Staff Member Created'), ('staff_role_changed', 'Staff Role Changed'), ('delegation_granted', 'Property Delegation Granted'), ('delegation_revoked', 'Property Delegation Revoked'), ('verification_submitted', 'Verification Documents Submitted'), ('verification_approved', 'Verification Approved by Admin'), ('verification_rejected', 'Verification Rejected by Admin')], max_length=30, verbose_name='Action Type')),
                ('details', models.JSONField(default=dict, help_text='Structured data about the action (e.g., old_role, new_role, property_id).', verbose_name='Action Details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='agencies.agency')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text='The user this action was performed on (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_actions_targeted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agency Activity Log',
                'verbose_name_plural': 'Agency Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgencyDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('national_id', models.CharField(blank=True, help_text='7 or 8 digit National ID.', max_length=8, null=True, validators=[apps.accounts.utils.validators.validate_national_id], verbose_name='National ID')),
                ('passport_number', models.CharField(blank=True, help_text='Alternative to National ID.', max_length=50, null=True, verbose_name='Passport Number')),
                ('email', models.EmailField(max_length=254, validators=[apps.accounts.utils.validators.validate_strict_email], verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, validators=[apps.accounts.utils.validators.validate_phone_number], verbose_name='Phone Number')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationality')),
                ('address', models.TextField(verbose_name='Residential Address')),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of agency ownership (0.00 - 100.00).', max_digits=5, verbose_name='Ownership Percentage')),
                ('is_primary_director', models.BooleanField(default=False, verbose_name='Primary Director')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20, verbose_name='Verification Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(help_text='The agency this director belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='agencies.agency')),
                ('user', models.ForeignKey(blank=True, help_text='Linked system user (if the director has an account).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agency Director',
                'verbose_name_plural': 'Agency Directors',
            },
        ),
        migrations.CreateModel(
            name='AgencyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='Registered Business Name')),
                ('registration_number', models.CharField(max_length=100, unique=True, verbose_name='Business Registration Number')),
                ('kra_pin', models.CharField(help_text='Format: A012345678B', max_length=11, unique=True, validators=[apps.accounts.utils.validators.validate_kra_pin], verbose_name='Business KRA PIN')),
                ('physical_address', models.TextField(verbose_name='Registered Physical Address')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('county', models.CharField(max_length=100, verbose_name='County')),
                ('contact_person_name', models.CharField(max_length=255, verbose_name='Contact Person Name')),
                ('contact_person_phone', models.CharField(max_length=15, validators=[apps.accounts.utils.validators.validate_phone_number], verbose_name='Contact Phone')),
                ('contact_person_email', models.EmailField(max_length=254, validators=[apps.accounts.utils.validators.validate_strict_email], verbose_name='Contact Email')),
                ('is_profile_complete', models.BooleanField(default=False, verbose_name='Profile Complete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.OneToOneField(help_text='The agency this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Agency Business Profile',
                'verbose_name_plural': 'Agency Business Profiles',
            },
        ),
        migrations.CreateModel(
            name='AgencyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Role Description')),
                ('permissions', models.JSONField(default=dict, help_text='Dictionary of granular permissions granted to this role.', verbose_name='Granted Permissions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(help_text='The agency that owns this custom role.', on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Custom Agency Role',
                'verbose_name_plural': 'Custom Agency Roles',
            },
        ),
        migrations.CreateModel(
            name='AgencyStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('property_manager', 'Property Manager'), ('field_agent', 'Field Agent'), ('maintenance_supervisor', 'Maintenance Supervisor'), ('operations_admin', 'Operations Admin'), ('caretaker', 'Caretaker')], max_length=30, verbose_name='Staff Role')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20, verbose_name='Employment Status')),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Phone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('terminated_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminated At')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('agency', models.ForeignKey(help_text='The agency this staff member belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='agencies.agency')),
                ('user', models.ForeignKey(blank=True, help_text='Linked system user account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_staff_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agency Staff Member',
                'verbose_name_plural': 'Agency Staff Members',
            },
        ),
        migrations.CreateModel(
            name='AgencyVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_registration_cert', models.FileField(blank=True, null=True, upload_to='agencies/verifications/business_reg/', verbose_name='Business Registration Certificate')),
                ('kra_pin', models.CharField(blank=True, help_text='Format: A012345678B', max_length=11, null=True, validators=[apps.accounts.utils.validators.validate_kra_pin], verbose_name='Business KRA PIN')),
                ('kra_tax_compliance_cert', models.FileField(blank=True, null=True, upload_to='agencies/verifications/tax/', verbose_name='KRA Tax Compliance Certificate')),
                ('agency_license', models.FileField(blank=True, help_text='Official agency operating license.', null=True, upload_to='agencies/verifications/licenses/', verbose_name='Estate Agents Registration Board (EARB) License')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('resubmit', 'Resubmission Required')], default='pending', max_length=20, verbose_name='Verification Status')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection/Resubmission Reason')),
                ('agency', models.OneToOneField(help_text='The agency being verified.', on_delete=django.db.models.deletion.CASCADE, related_name='verification_record', to='agencies.agency')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this verification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_verifications_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agency Verification',
                'verbose_name_plural': 'Agency Verifications',
            },
        ),
        migrations.CreateModel(
            name='DelegatedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegation_type', models.CharField(choices=[('full', 'Full Delegation (Tenants, Payments, Maintenance, Operations)'), ('partial', 'Partial Delegation (e.g., Maintenance & Tenants only)'), ('view_only', 'View Only (Assistance & Reporting)')], default='partial', max_length=20, verbose_name='Delegation Type')),
                ('custom_permissions', models.JSONField(blank=True, default=dict, help_text='Specific permission overrides for this delegation.', verbose_name='Custom Permissions')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked by Landlord'), ('expired', 'Contract Expired'), ('pending', 'Pending Agency Acceptance')], default='pending', max_length=20, verbose_name='Delegation Status')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
                ('revocation_reason', models.TextField(blank=True, null=True, verbose_name='Revocation Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(help_text='The agency receiving delegation rights.', on_delete=django.db.models.deletion.CASCADE, related_name='delegated_properties', to='agencies.agency')),
                ('property_ref', models.ForeignKey(help_text='The property being delegated.', on_delete=django.db.models.deletion.CASCADE, related_name='agency_delegations', to='properties.property')),
                ('revoked_by', models.ForeignKey(blank=True, help_text='User who revoked this delegation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_delegations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delegated Property',
                'verbose_name_plural': 'Delegated Properties',
            },
        ),
        migrations.CreateModel(
            name='AgencyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Global Agency Access'), ('property_specific', 'Specific Delegated Properties')], default='global', max_length=30, verbose_name='Permission Scope')),
                ('permissions', models.JSONField(default=dict, help_text='Explicit permission overrides for this staff member.', verbose_name='Granted Permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_permissions', to='agencies.agency')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_agency_permissions', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(help_text='The staff member receiving these permissions.', on_delete=django.db.models.deletion.CASCADE, related_name='explicit_permissions', to='agencies.agencystaff')),
                ('delegated_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_permissions', to='agencies.delegatedproperty')),
            ],
            options={
                'verbose_name': 'Agency Staff Permission',
                'verbose_name_plural': 'Agency Staff Permissions',
            },
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['status', 'is_active'], name='agencies_ag_status_9af85a_idx'),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['registration_number'], name='agencies_ag_registr_6713d1_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyactivitylog',
            index=models.Index(fields=['agency', 'timestamp'], name='agencies_ag_agency__a30fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyactivitylog',
            index=models.Index(fields=['performed_by', 'timestamp'], name='agencies_ag_perform_36537e_idx'),
        ),
        migrations.AddIndex(
            model_name='agencydirector',
            index=models.Index(fields=['agency', 'verification_status'], name='agencies_ag_agency__db2c0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='agencydirector',
            constraint=models.CheckConstraint(check=models.Q(('national_id__isnull', False), ('passport_number__isnull', False), _connector='OR'), name='director_must_have_id_or_passport'),
        ),
        migrations.AddConstraint(
            model_name='agencyrole',
            constraint=models.UniqueConstraint(fields=('agency', 'name'), name='unique_role_name_per_agency'),
        ),
        migrations.AddIndex(
            model_name='agencystaff',
            index=models.Index(fields=['agency', 'status'], name='agencies_ag_agency__b18be5_idx'),
        ),
        migrations.AddIndex(
            model_name='agencystaff',
            index=models.Index(fields=['user', 'status'], name='agencies_ag_user_id_daa87b_idx'),
        ),
        migrations.AddConstraint(
            model_name='agencystaff',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('agency', 'user'), name='unique_staff_user_per_agency'),
        ),
        migrations.AddIndex(
            model_name='agencyverification',
            index=models.Index(fields=['status'], name='agencies_ag_status_4d2266_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyverification',
            index=models.Index(fields=['agency', 'status'], name='agencies_ag_agency__2fbaeb_idx'),
        ),
        migrations.AddIndex(
            model_name='delegatedproperty',
            index=models.Index(fields=['agency', 'status'], name='agencies_de_agency__10cecc_idx'),
        ),
        migrations.AddIndex(
            model_name='delegatedproperty',
            index=models.Index(fields=['property_ref', 'status'], name='agencies_de_propert_da99c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='delegatedproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('property_ref', 'agency'), name='unique_active_delegation_per_property_agency'),
        ),
        migrations.AddConstraint(
            model_name='agencypermission',
            constraint=models.UniqueConstraint(fields=('staff_member', 'scope', 'delegated_property'), name='unique_permission_per_staff_scope_property'),
        ),
    ]
