# Generated by Django 5.0.6 on 2026-06-30 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('properties', '0008_alter_location_city_alter_location_county'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencystaff',
            options={'verbose_name': 'Staff Member', 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.RemoveConstraint(
            model_name='agencystaff',
            name='unique_staff_user_per_agency',
        ),
        migrations.RemoveField(
            model_name='delegatedproperty',
            name='custom_permissions',
        ),
        migrations.RemoveField(
            model_name='delegatedproperty',
            name='delegation_type',
        ),
        migrations.AlterField(
            model_name='agencystaff',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='The agency this staff member belongs to. Null if assigned directly by a landlord.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='agencies.agency'),
        ),
        migrations.AlterField(
            model_name='agencystaff',
            name='role',
            field=models.CharField(choices=[('property_manager', 'Property Manager'), ('agent', 'Agent'), ('caretaker', 'Caretaker')], max_length=30, verbose_name='Staff Role'),
        ),
        migrations.AlterField(
            model_name='agencystaff',
            name='user',
            field=models.ForeignKey(default=1, help_text='Linked system user account.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delegatedproperty',
            name='agency',
            field=models.ForeignKey(help_text='The agency receiving 100% management rights.', on_delete=django.db.models.deletion.CASCADE, related_name='delegated_properties', to='agencies.agency'),
        ),
        migrations.AlterField(
            model_name='delegatedproperty',
            name='property_ref',
            field=models.ForeignKey(help_text='The property being fully delegated.', on_delete=django.db.models.deletion.CASCADE, related_name='agency_delegations', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='delegatedproperty',
            name='status',
            field=models.CharField(choices=[('active', 'Active (Full Control Transferred)'), ('revoked', 'Revoked by Landlord'), ('expired', 'Contract Expired'), ('pending', 'Pending Agency Acceptance')], default='pending', max_length=20, verbose_name='Delegation Status'),
        ),
        migrations.AddIndex(
            model_name='agencystaff',
            index=models.Index(fields=['role', 'status'], name='agencies_ag_role_510dc0_idx'),
        ),
    ]
