# Generated by Django 5.0.6 on 2026-06-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_alter_agencystaff_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgencyPermission',
        ),
    ]
