# Generated by Django 5.0.6 on 2026-06-12 23:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g., plumbing, electrical, structural', max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default_sla_hours', models.PositiveIntegerField(default=72, help_text='Default resolution SLA in hours')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Maintenance Category',
                'verbose_name_plural': 'Maintenance Categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_date', models.DateField()),
                ('findings', models.TextField(blank=True, help_text='Condition report notes')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_inspections', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Maintenance Inspection',
                'verbose_name_plural': 'Maintenance Inspections',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('sla_due_at', models.DateTimeField(blank=True, help_text='Auto-calculated based on category SLA + priority multiplier', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(help_text='Primary responder (caretaker/agent/technician)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_tasks', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='maintenance.maintenancecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_requests', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='properties.property')),
                ('tenancy', models.ForeignKey(blank=True, help_text='Nullable: caretakers can report in vacant units', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='tenancy.tenancy')),
                ('unit', models.ForeignKey(help_text='Every request must be tied to a unit', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Maintenance Request',
                'verbose_name_plural': 'Maintenance Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=20)),
                ('file_url', models.URLField(help_text='Cloud storage path (S3/Spaces)')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_before_after', models.BooleanField(default=False, help_text='True = proof of resolution/completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_attachments', to='maintenance.maintenancerequest')),
            ],
            options={
                'verbose_name': 'Maintenance Media',
                'verbose_name_plural': 'Maintenance Media Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('media_uploaded', 'Media Uploaded'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('sla_breach', 'SLA Breach'), ('reassigned', 'Reassigned')], db_index=True, max_length=30)),
                ('previous_value', models.JSONField(blank=True, help_text='Snapshot before change', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='Snapshot after change', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_history', to='maintenance.maintenancerequest')),
            ],
            options={
                'verbose_name': 'Maintenance Audit History',
                'verbose_name_plural': 'Maintenance Audit Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_type', models.CharField(choices=[('caretaker', 'Caretaker'), ('agent', 'Agent'), ('technician', 'External Technician')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Acknowledgment'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('reassigned', 'Reassigned')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_assignments', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='maintenance.maintenancerequest')),
            ],
            options={
                'verbose_name': 'Maintenance Assignment',
                'verbose_name_plural': 'Maintenance Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='maintenance.maintenancerequest')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Update',
                'verbose_name_plural': 'Maintenance Updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['status', 'priority'], name='maintenance_status_b5e015_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['property', 'unit'], name='maintenance_propert_0aae5e_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['assigned_to', 'status'], name='maintenance_assigne_70195a_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['sla_due_at', 'status'], name='maintenance_sla_due_73c12b_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancehistory',
            index=models.Index(fields=['request', 'event_type'], name='maintenance_request_68eab4_idx'),
        ),
    ]
