# Generated by Django 5.0.6 on 2026-06-12 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('rental', 'Rental Application'), ('transfer', 'Transfer Application'), ('eviction_notice', 'Eviction Notice (Tenant Initiated)')], default='rental', max_length=20, verbose_name='Application Type')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('escalated', 'Escalated to Manager'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(help_text='The user submitting the application.', on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(help_text='The target property for this application.', on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, help_text='The specific target unit (nullable for property-wide eviction notices).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated to Manager')], max_length=20, verbose_name='Decision')),
                ('approver_role', models.CharField(help_text="e.g., 'agent', 'manager', 'landlord'. Stored for historical audit.", max_length=20, verbose_name='Approver Role at Time of Decision')),
                ('reason', models.TextField(blank=True, help_text='Justification for approval, rejection, or escalation.', null=True, verbose_name='Decision Reason')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(help_text='The application this decision applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='applications.application')),
                ('approver', models.ForeignKey(help_text='The Agent, Manager, or Landlord who made this decision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_decisions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Decision',
                'verbose_name_plural': 'Application Decisions',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('system_validation', 'System Validation Note'), ('agent_review', 'Agent Review Note'), ('manager_remark', 'Manager Remark'), ('escalation_reason', 'Escalation Reason')], default='agent_review', max_length=30, verbose_name='Note Type')),
                ('content', models.TextField(help_text='The actual note, validation result, or remark.', verbose_name='Note Content')),
                ('is_confidential', models.BooleanField(default=False, help_text='If true, only visible to managers/landlords, not general agents.', verbose_name='Is Confidential')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(help_text='The application this note belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.application')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the note (null for system-generated notes).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_notes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Note',
                'verbose_name_plural': 'Application Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvictionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_period_days', models.PositiveIntegerField(help_text='Number of days of notice being given (e.g., 30, 60).', verbose_name='Notice Period (Days)')),
                ('intended_vacate_date', models.DateField(help_text='The exact date the tenant plans to hand over the unit.', verbose_name='Intended Vacate Date')),
                ('reason_for_leaving', models.TextField(blank=True, help_text='Optional explanation for the early termination or notice.', null=True, verbose_name='Reason for Leaving')),
                ('forwarding_address', models.TextField(blank=True, help_text='Where the tenant can be reached for deposit refund or final correspondence.', null=True, verbose_name='Forwarding Address')),
                ('application', models.OneToOneField(help_text='The base application record this eviction notice extends.', on_delete=django.db.models.deletion.CASCADE, related_name='eviction_details', to='applications.application')),
            ],
            options={
                'verbose_name': 'Eviction Notice Application',
                'verbose_name_plural': 'Eviction Notice Applications',
            },
        ),
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self Employed'), ('student', 'Student'), ('unemployed', 'Unemployed')], help_text='Current employment status of the applicant.', max_length=20, verbose_name='Employment Status')),
                ('desired_move_in_date', models.DateField(help_text='The date the applicant wishes to occupy the unit.', verbose_name='Desired Move-in Date')),
                ('meets_deposit_requirement', models.BooleanField(default=False, verbose_name='Meets Deposit Requirement')),
                ('meets_service_charge_requirement', models.BooleanField(default=False, verbose_name='Meets Service Charge Requirement')),
                ('has_blocking_flags', models.BooleanField(default=False, verbose_name='Has Blocking Flags (e.g., arrears)')),
                ('application', models.OneToOneField(help_text='The base application record this rental request extends.', on_delete=django.db.models.deletion.CASCADE, related_name='rental_details', to='applications.application')),
            ],
            options={
                'verbose_name': 'Rental Application',
                'verbose_name_plural': 'Rental Applications',
            },
        ),
        migrations.CreateModel(
            name='TransferApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text="Tenant's justification for the transfer request.", verbose_name='Reason for Transfer')),
                ('has_unpaid_critical_arrears', models.BooleanField(default=False, verbose_name='Has Unpaid Critical Arrears')),
                ('transfer_allowed_by_permissions', models.BooleanField(default=False, verbose_name='Transfer Allowed by Permissions')),
                ('application', models.OneToOneField(help_text='The base application record this transfer extends.', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_details', to='applications.application')),
                ('current_tenancy', models.ForeignKey(help_text='The active tenancy the tenant is transferring from.', on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_requests', to='tenancy.tenancy')),
                ('from_property', models.ForeignKey(help_text='The property the tenant is currently occupying.', on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_applications', to='properties.property')),
                ('from_unit', models.ForeignKey(help_text='The specific unit the tenant is currently occupying.', on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_applications', to='properties.unit')),
                ('to_property', models.ForeignKey(help_text='The destination property.', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_applications', to='properties.property')),
                ('to_unit', models.ForeignKey(help_text='The specific destination unit.', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_applications', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Transfer Application',
                'verbose_name_plural': 'Transfer Applications',
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'status'], name='application_applica_b6966f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['property', 'status'], name='application_propert_968e01_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationnote',
            index=models.Index(fields=['application', 'created_at'], name='application_applica_2efad0_idx'),
        ),
    ]
