# Generated by Django 5.0.6 on 2026-06-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('escalated', 'Escalated to Manager'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('completed', 'Completed (Converted to Tenancy)')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
