# Generated by Django 5.0.6 on 2026-06-16 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'System Administrator'), ('landlord', 'Landlord'), ('agency', 'Agency'), ('agent', 'Agent'), ('caretaker', 'Caretaker'), ('tenant', 'Tenant')], help_text='The user role this dashboard configuration applies to.', max_length=20, unique=True, verbose_name='Target Role')),
                ('name', models.CharField(max_length=100, verbose_name='Dashboard Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('widget_configuration', models.JSONField(default=dict, help_text='Defines which KPIs, charts, and tables are visible to this role.', verbose_name='Widget Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Configuration',
                'verbose_name_plural': 'Dashboard Configurations',
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Widget Name')),
                ('widget_type', models.CharField(choices=[('kpi_card', 'KPI Card (e.g., Total Revenue)'), ('chart', 'Chart (e.g., Occupancy Trend)'), ('table', 'Data Table (e.g., Recent Payments)'), ('alert', 'Alert List (e.g., Overdue Maintenance)')], max_length=20, verbose_name='Widget Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('data_source', models.CharField(help_text='The backend service method that populates this widget.', max_length=255, verbose_name='Data Source Service')),
                ('frontend_config', models.JSONField(default=dict, help_text='UI settings like chart type, color, currency formatting, etc.', verbose_name='Frontend Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Report Title')),
                ('report_type', models.CharField(choices=[('financial', 'Financial & Revenue Report'), ('occupancy', 'Occupancy & Vacancy Report'), ('tenancy', 'Tenancy & Tenant History Report'), ('maintenance', 'Maintenance & SLA Report'), ('marketplace', 'Marketplace & Lead Analytics'), ('applications', 'Application Conversion Report')], max_length=20, verbose_name='Report Type')),
                ('parameters', models.JSONField(default=dict, help_text='Filters and criteria used to generate this report.', verbose_name='Report Parameters')),
                ('status', models.CharField(choices=[('pending', 'Pending Generation'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('file_url', models.URLField(blank=True, help_text='Link to the generated PDF or Excel file in cloud storage.', null=True, verbose_name='Exported File URL')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(help_text='User who requested this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Generation Request',
                'verbose_name_plural': 'Report Generation Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Schedule Title')),
                ('report_type', models.CharField(choices=[('financial', 'Financial & Revenue Report'), ('occupancy', 'Occupancy & Vacancy Report'), ('tenancy', 'Tenancy & Tenant History Report'), ('maintenance', 'Maintenance & SLA Report')], max_length=20, verbose_name='Report Type')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='Frequency')),
                ('parameters', models.JSONField(default=dict, help_text='Filters and criteria applied to every scheduled run.', verbose_name='Report Parameters')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Next Run At')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Run At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who configured this schedule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'ordering': ['-next_run_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_data', models.JSONField(help_text='The computed KPIs, charts, and tabular data at the time of generation.', verbose_name='Snapshot Data')),
                ('taken_at', models.DateTimeField(auto_now_add=True, help_text='Exact timestamp when this data was aggregated and locked.', verbose_name='Snapshot Taken At')),
                ('report', models.OneToOneField(help_text='The parent report generation request this snapshot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='reports.report')),
            ],
            options={
                'verbose_name': 'Report Data Snapshot',
                'verbose_name_plural': 'Report Data Snapshots',
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('marketplace_view', 'Marketplace Listing Viewed'), ('application_started', 'Rental Application Started'), ('application_submitted', 'Rental Application Submitted'), ('payment_initiated', 'Payment Initiated'), ('payment_success', 'Payment Successful'), ('maintenance_requested', 'Maintenance Requested'), ('dashboard_accessed', 'Dashboard Accessed')], db_index=True, max_length=50, verbose_name='Event Type')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context like search filters, device info, or conversion value.', verbose_name='Event Metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Event Timestamp')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the event (null for anonymous marketplace views).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='reports_ana_event_t_563545_idx'), models.Index(fields=['user', 'event_type'], name='reports_ana_user_id_affe45_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_at_time', models.CharField(help_text='The role the user had when this snapshot was taken.', max_length=20, verbose_name='User Role at Time')),
                ('snapshot_data', models.JSONField(help_text='The computed KPIs, chart data, and widget states at the time of capture.', verbose_name='Dashboard Data')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Exact timestamp when this dashboard state was frozen.', verbose_name='Captured At')),
                ('user', models.ForeignKey(help_text='The user this dashboard snapshot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Snapshot',
                'verbose_name_plural': 'Dashboard Snapshots',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['user', 'captured_at'], name='reports_das_user_id_1207cd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'status'], name='reports_rep_report__4cebb9_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_by', 'created_at'], name='reports_rep_generat_b60f00_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['is_active', 'next_run_at'], name='reports_rep_is_acti_c0e6a8_idx'),
        ),
    ]
